version: "3.8"

services:
  db:
    image: postgres:12.3
    env_file: .env
    restart: on-failure
  annotation-service:
    image: annotation-service:0.1
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    command: bash -c "python /manage.py migrate --noinput && uwsgi /uwsgi.ini"
    build:
      context: ..
      dockerfile: docker/Dockerfile
